version: "3.3"
services:
  app-server:
    build:
      dockerfile: php.Dockerfile
      context: .
    restart: on-failure
    volumes:
      - "./html/:/var/www/html/"
    ports:
      - "8080:80"

  mysql-server:
    image: mysql:latest
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: root00--
    volumes:
      - ./mysql/mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: on-failure
    environment:
      PMA_HOST: mysql-server
      PMA_USER: root
      PMA_PASSWORD: root00--
    ports:
      - "5000:80"
volumes:
  mysql-data:
