version: "3.3"
services:
  app-server:
    build:
      dockerfile: php.Dockerfile
      context: .
    restart: on-failure
    volumes:
      - "./html/:/var/www/html/"
    ports:
      - "8080:80"

  mysql-server:
    build:
      dockerfile: mysql.Dockerfile
      context: .
    restart: on-failure
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root00--
      MYSQL_DATABASE: wildeklawer_tk
      MYSQL_USER: wkadmin
      MYSQL_PASSWORD: Wk@dmin1

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: on-failure
    environment:
      PMA_HOST: mysql-server
      PMA_USER: root
      PMA_PASSWORD: root00--
    ports:
      - "99:80"
volumes:
  mysql-data:
